#!/bin/csh

# foreach band (29 30 31 32)
# cat << EOF > /tmp/dummy.input
# $band
# EOF
#   ~/lib/fermi/cretdata2 < /tmp/dummy.input
#   /bin/mv fort.7 band$band.dat
#   /bin/rm /tmp/dummy.input
#   /usr/bin/make -f Makedmgo BAND=$band
# end

foreach band (29 30 31 32)
  make -f Makedmgo BAND=$band
end
