#!/Volumes/exHD/funa/local/bin/ruby
home = ENV['HOME'] + '/'
$LOAD_PATH.push(home + '../funa/tools/module')
require 'KansaiAnalysis'
include KansaiUtil
target = nil
if ARGV.empty?
  target = fort2_to_orig
else
  target = ARGV[0]
end

unless target.nil?
  KansaiAnalysis.new(target).occupations.each_with_index do |ieig, ind|
    print "band index = #{ind + 1} : occupation number = #{ieig}\n"
  end
end
