#!/Volumes/exHD/funa/local/bin/python3
import sys
from KansaiPackage.OutAnalysis.CheckIteration import CheckIteration

argv = sys.argv
if len(argv) < 2:
    print("usage check_iter [filename]")
else:
    filename = argv[1]
    CheckIteration(filename)
