#!/usr/bin/env python3
#
#
from KansaiPackage.KSfiles.ParseFort1 import ParseFort1
from KansaiPackage.PointGroup.PointGroup import PointGroup
import os.path

fort1 = './fort.1'

if not os.path.isfile(fort1):
    print("fort.1 is not found.")
    exit()

fort1_obj = ParseFort1(fort1)
il = fort1_obj.il
generator_list = fort1_obj.generator_list

pg_obj = PointGroup(il, generator_list)
print("================= check_pg info ======================")
print()
print("  Crystal System :  {}".format(pg_obj.crystal_system))
print("  Bravais Lattice:  {}".format(pg_obj.bravais_lattice))
print("  Point Group    :  {}".format(pg_obj.name))
print()
pg_obj.show_generator_list_info()
pg_obj.show_element_list_info()
