#!/usr/bin/env ruby
#
# check convergence
#
home = ENV['HOME'] + '/'
$LOAD_PATH.push(home + 'tools/module')
require 'KSDstUtil'

dstfile = KSDstUtil.new(ARGV).dstfile

open(dstfile, 'r').each do |fin|
  fin.each_line do |line|
    print line
  end
end
