#!/Volumes/exHD/funa/local/bin/ruby
#
# analysis tool for results for levsts
#   ver. 2.0
#     written by HF in Kobe 14th April 2017
#
#
home = ENV['HOME'] + '/../funa/'
$LOAD_PATH.push(home + 'tools/module')
require 'DisplayLevsts'

if ARGV.empty?
  print "usage: check_levsts [filename1, filename2, ...]\n"
  exit
else
  obj = nil
  search_files = []
  ARGV.each do |filename|
    if filename =~ /\d-\d/
      pre, suf = filename.split('-')
      from = pre.match(/\d+/).to_s
      to = suf.match(/\d+/).to_s
      prefix, suffix = filename.split(from + '-' + to)
      from.to_i.upto(to.to_i).each do |i|
        search_files.push(prefix + i.to_s + suffix)
      end
    else
      search_files.push(filename)
    end
  end
  search_files.each_with_index do |filename, ind|
    if ind == 0
      obj = DisplayLevsts.new(filename)
    else
      obj.add_outfile(filename)
    end
  end
  obj.display
end
