#!/Volumes/exHD/funa/local/bin/python3
from KansaiPackage.KSfiles.ParseCharge import ParseCharge
import sys

argv = sys.argv

if len(sys.argv) < 2:
    datafile = 'fort.30'
else:
    datafile = argv[1]

charge_info = ParseCharge(datafile)
charge_info.show_info(colored=True)
charge_info.show_core_info(colored=True)
