#!/Volumes/exHD/funa/local/bin/ruby

require 'optparse'
home = ENV['HOME'] + '/'
$LOAD_PATH.push(home + '../funa/tools/module')
require 'LatestData'
require 'fileutils'

prefix = 'fl'
suffix = '.out'
dir = '..'

if ARGV.empty?
  latest_index = LatestData.new(prefix, suffix, dir).search_index.to_i
else
  target = ARGV[0]
  latest_index =
    if target =~ /#{prefix}/
      target.split(prefix)[-1].split('.')[0].to_i
    else
      target.to_i
    end
end
latest_infile = dir + '/' + prefix + latest_index.to_s + '.dat'

unless File.exist?(latest_infile)
  print "===== Error =====\n"
  print "file:#{latest_infile} is not found.\n"
  exit
end

new_prefix = dir + '/' + prefix + (latest_index + 1).to_s
new_infile = new_prefix + '.dat'
new_outfile = new_prefix + '.out'
print "  File copy from #{latest_infile} to #{new_infile}\n"
if File.exist?(new_infile)
  print "   -> #{new_infile} has been overwritten.\n"
  FileUtils.rm(new_infile)
end
FileUtils.cp(latest_infile, new_infile)
if File.exist?(new_outfile)
  print "   -> #{new_outfile} has been deleted.\n"
  FileUtils.rm(new_outfile)
end
