#!/Volumes/exHD/funa/local/bin/ruby
#
#
home = ENV['HOME']
$LOAD_PATH.push("#{home}/../funa/tools/module")
require 'SCF_init'

if ARGV.size == 0
  initdir = '../../lapw/wk'
else
  initdir = ARGV[0] + '/wk'
end
filelist = [1, 30, 35]

prefix = 'fw'
suffix = '.dat'

results_list = ['fchg', 'dst', 'eld', 'esd', 'fpot']

dir = '..'
data_prefix = 'fort.'


configure = {
  initdir: initdir,
  data_prefix: 'fort.',
  filelist: filelist,
  prefix: prefix,
  suffix: suffix,
  dir: dir,
  results_list: results_list
} 

SCF_init.new(configure)

configure[:prefix] = 'fl'
SCF_init.new(configure)
