#!/Volumes/exHD/funa/local/bin/ruby
#
# recover fl? data
#   written by Hiroki Funashima
#
home = ENV['HOME']
$LOAD_PATH.push("#{home}/../funa/tools/module")
require 'RecoverCalc'
index = 1

linkfiles = {
  45 => 'fpot',
  32 => 'fchg',
  16 => 'dst',
  28 => 'eld',
  29 => 'esd'
}

tmpfiles = [20, 22, 24, 25, 26, 27, 40, 61, 62]

configure = {
  index: index,
  linkfiles: linkfiles,
  tmpfiles: tmpfiles,
  dir: '..',
  prefix: 'fw',
  suffix: '.dat'
}
RecoverCalc.new(configure)
next_out = '../fl1.out'
ARGV.shift
if File.exist?(next_out)
  print "\n"
  print "i found next output #{next_out}.\n"
  print "Do you hope to delete #{next_out}? [y/(n)]\n"
  ans = gets
  unless ans.nil?
    if ans.chomp.strip.downcase =~ /^y/
      FileUtils.rm(next_out)
      print " -> #{next_out} has been deleted.\n"
    end
  end
end
