#!/Volumes/exHD/funa/local/bin/ruby
#
#
home = ENV['HOME']
$LOAD_PATH.push("#{home}/../funa/tools/module")
require 'ExecSCFseries'

package = 'xslgo'

if ARGV.empty?
  print "Usage: ilapw iter_min [iter_max]\n"
  exit
end

min_iter, max_iter = ARGV
max_iter = min_iter if max_iter.nil?

configure = {
  min_iter: min_iter,
  max_iter: max_iter,
  package: package
}

ExecSCFseries.new(configure)
