#!/usr/bin/env python3
import argparse
import glob
import os
import shutil


class Init2Lapw(object):
    def __init__(self, args):
        self.dirname = args.init_dir
        self.clean_files = args.clean
        self.main()

    def main(self):
        if self.clean_files:
            self.clean()
        self.setup()

    def setup(self):
        wkdir = './wk'
        for fortfile in ['fort.1', 'fort.30', 'fort.35']:
            origfile = self.dirname + '/' + fortfile
            newfile = wkdir + '/' + fortfile
            if not os.path.isdir(wkdir):
                os.mkdir(wkdir)
            if os.path.isfile(origfile):
                print('copy from {0} to {1}'.format(origfile, newfile))
                if os.path.isfile(newfile):
                    os.remove(newfile)
                shutil.copy2(origfile, newfile)

    def clean(self):
        for suffix in ['.dat', '.out']:
            file_list = glob.glob('sl*{}'.format(suffix))
            for filename in file_list:
                if os.path.isfile(filename):
                    os.remove(filename)
        file_list = glob.glob('./wk/fort.*') + glob.glob('wk/sl*.log')
        for filename in file_list:
            if os.path.isfile(filename):
                os.remove(filename)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(prog="init2lapw",
                                     usage="setup and initialization for lapw",
                                     add_help=True)

    parser.add_argument('init_dir',
                        nargs='?',
                        action='store',
                        default='../init')
    parser.add_argument('--clean',
                        action='store_true',
                        help='all clean files(remove sl??.dat, wk/fort.*, wk/sl*.log)')

    Init2Lapw(parser.parse_args())
