#!/usr/bin/env python3
import argparse
import os
from KansaiPackage.makeprp.MakePrp import MakePrp
from KansaiPackage.makeprp.GenInit import GenInit

if __name__ == '__main__':

    configfile = 'crystal.in'
    prpin = 'prp.inp'

    parser = argparse.ArgumentParser(prog="makeprp",
                                     usage="setup for taprpmn ",
                                     add_help = True)
    parser.add_argument('--init',
                        action='store_true',
                        help='generate template inputfile for makeprp')
    args =parser.parse_args()
    if not os.path.isfile(configfile):
        print('generate template imputfile, crystal.in')
        print('edit it.')
        GenInit(configfile)
    else:
        if args.init:
            GenInit(configfile)
        else:
            MakePrp(configfile, prpin)
