#!/usr/bin/env python3
#
# == orderek ==
#   original code was written by H.Harima
#   This version is implementd version written in Python
#   from scratch by Hiroki Funashima to test spintexture suite
#

from KansaiPackage.OrderEk.mod_orderek import mod_orderek
import os
import sys

argv = sys.argv
argc = len(argv)

if argc < 2:
    fort2 = 'fort.2'
else:
    fort2 = argv[1]

for target in ['wk/fort.1', 'fort.1']:
    if os.path.isfile(target):
        fort1 = target
        break
else:
    print("======= Error =======")
    print("fort.1 is not found")
    exit(1)


if __name__ == "__main__":
    mod_orderek(fort1, fort2).standard_input().main()
