#!/Volumes/exHD/funa/local/bin/python3

import sys
import argparse # option
from py_module.KsInputData import *
from py_module.MTPDataIO import *
from py_module.PlotMTP import *

parser = argparse.ArgumentParser(description='plot logarithmic derivative')
parser.add_argument('filename', nargs='?')
parser.add_argument('-i', '--iteration', nargs='?')
parser.add_argument('--rmin', nargs='?')
parser.add_argument('--rmax', nargs='?')
args = parser.parse_args()

inputObj = KsInputData('logdrv.conf', args)
dataObj = MTPDataIO(inputObj)
plotObj = PlotMTP(dataObj).draw()
