#!/Volumes/exHD/funa/local/bin/python3
#
# plot for core level
#   written by Hiroki Funashima
#

import sys
import argparse # option
from py_module.ParseFort1 import *
from py_module.KsInputData import *
from py_module.PlotCoreLevel import *

parser = argparse.ArgumentParser(description='plot logarithmic derivative')
parser.add_argument('filename', nargs='?')
parser.add_argument('-i', '--iteration', nargs='?')

args = parser.parse_args()
inputObj = KsInputData('logdrv.conf', args)
PlotCoreLevel(inputObj).draw()
