#!/usr/bin/env python3
from KansaiPackage.OutAnalysis.PlotCharge import PlotCharge
import sys

argv = sys.argv

if len(sys.argv) < 2:
    datafile = 'fort.30'
else:
    datafile = argv[1]

PlotCharge(datafile)
