#!/Volumes/exHD/funa/local/bin/ruby
#
#
home = ENV['HOME']
$LOAD_PATH.push("#{home}/../funa/tools/module")
require 'SCF_init'
if ARGV.size == 0
  initdir = '../../init'
else
  initdir = ARGV[0]
end
filelist = [1, 30, 35]

prefix = 'sl'
suffix = '.dat'

results_list = ['chg', 'dst', 'eld', 'esd', 'pot']

dir = '..'
data_prefix = 'fort.'


configure = {
  initdir: initdir,
  data_prefix: 'fort.',
  filelist: filelist,
  prefix: prefix,
  suffix: suffix,
  dir: dir,
  results_list: results_list
} 

SCF_init.new(configure)
