#!/usr/bin/env python3
#
# front end of ayband written in Fortran
#   written by Hiroki Funashima in kobe
#
from KansaiPackage.aydos.xAydos import xAydos
import os.path
import sys

argv = sys.argv
argc = len(argv)
default_input = 'dos.in'
if argc < 2:
    if os.path.isfile(default_input):
        configfile = default_input
        xAydos(configfile)
    else:
        print('usage: xaydos [configure file]')
        exit()
else:
    configfile = argv[1]
    xAydos(configfile)
