#!/usr/bin/env ruby
#
# modifiled flgo
#   written by Hiroki Funashima, Kobe University
#

home = ENV['HOME'] + '/'

#-------------------------------------------------
#
# your KANSAI package for FLAPW
#
kansai = home + 'KANSAI12x/flapw'
#kansai = home + 'KANSAI12xsp/flapw'

#-------------------------------------------------


$LOAD_PATH.push("#{home}/tools/module")

require 'ExecuteSCF'
require 'CheckTmpFiles'
require 'DisplayEnvs'

#if ARGV.size > 0
#  index = ARGV[0]
#else
#  index = nil
#end

linkfiles = {
  45 => 'fpot',
  32 => 'fchg',
  16 => 'dst',
  28 => 'eld',
  29 => 'esd',
  75 => 'sgm'
}

previous_files = {
  45 => 'potential',
  32 => 'charge density',
  1 => 'crystal data'
}

tmpfiles = [20, 22, 24, 25, 26, 27, 40, 61, 62]

configure = {
  kansai: kansai,
  outcheck: true,
  exec_overwrite: true,
  executable: 'tflapwem',
  index: '',
  linkfiles: linkfiles,
  dir: '..',
  prefix: 'fel',
  suffix: '.dat',
  previous_files: previous_files,
  tmpfiles: tmpfiles
}

if index.nil?
  require 'GetInputFile'
  configure[:index] = GetInputFile.new(configure).index
end

DisplayEnvs.new(configure)
tmp = CheckTmpFiles.new(configure)
tmp.linking
ExecuteSCF.new(configure)
tmp.deleting
